feat: added gRPC specification
poorfrombabylon/KION pull request #2
Opened 2022-04-23 23:22 UTC by poorfrombabylon

2022-04-24 19:06 UTC, Nikitosina requested changes

2022-04-24 19:06 UTC, Nikitosina commented on specs/proto/user_service.proto
> +message GetOrCreateRecordRequest{
Может назовем просто `GetRecordRequest`? Просто по-дефолту если нет записи пусть создает?)
И разве при создании запроса мы должны передавать `video_time`? В чем тогда суть респонса будет вообще?

2022-04-24 19:06 UTC, Nikitosina commented on domain/model.go
> +	videoTime string
А почему тип `string`? Не знаю как в мире бэкенда такое делается, но я бы предложил хранить int'ом в секундах

2022-04-24 19:08 UTC, poorfrombabylon commented on specs/proto/user_service.proto
> +message GetOrCreateRecordRequest{
короче я предлагаю разделить на 2-3 метода:  создание записи в бд, получение и что нибудь еще

2022-04-24 19:09 UTC, poorfrombabylon commented on domain/model.go
> +	videoTime string
кстати база согласен

2022-04-24 19:12 UTC, Nikitosina commented on specs/proto/user_service.proto
> +message GetOrCreateRecordRequest{
Да, давай, а то названия методов какие-то непрозрачные получаются)

2022-05-09 14:47 UTC, Travonka commented on specs/proto/user_service.proto
> +  rpc CreateRecord(CreateRecordRequest) returns (CreateRecordResponse) {}
зачем скобочки в конце?

2022-05-09 14:47 UTC, Travonka commented on specs/proto/user_service.proto
> +  rpc GetRecord(GetRecordRequest) returns (GetRecordResponse) {}
зачем скобочки в конце?

2022-05-09 14:47 UTC, Travonka commented on specs/proto/user_service.proto
> +  string video_time = 1;
Почему time string, а не duration?

2022-05-09 14:47 UTC, Travonka commented on specs/proto/user_service.proto
> +  string video_time = 4;
Почему time string, а не duration?

2022-05-09 14:47 UTC, Travonka commented on domain/model.go
> +	videoTime string
Почему time string, а не duration?

2022-05-09 15:16 UTC, poorfrombabylon commented
рот ебал

2022-05-09 15:17 UTC, Travonka commented on specs/proto/user_service.proto
> +option go_package = "../gen";
../gen?

2022-05-09 15:20 UTC, Travonka commented on specs/proto/user_service.proto
> +  int32 second = 3;
hourS, minuteS, но second

2022-05-09 15:20 UTC, poorfrombabylon commented on specs/proto/user_service.proto
> +  int32 second = 3;
хахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахаххахахахахахах

2022-05-09 15:52 UTC, Travonka commented
Аппрув

2022-05-09 15:54 UTC, merged